version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    path:
      data: /var/data/elasticsearch
      logs: /var/log/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=Elastic
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 2g
    networks:
      - elastic

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge